"""init

Revision ID: 355fa847a82f
Revises: 
Create Date: 2026-02-05 21:14:00.310870

"""
from alembic import op
import sqlalchemy as sa



revision = '355fa847a82f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('organization_name', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.Column('project_progress', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('project_progress BETWEEN 0 AND 100', name='projects_progress_range'),
    sa.PrimaryKeyConstraint('organization_name', 'project_id'),
    sa.UniqueConstraint('organization_name', 'project_name', name='projects_org_name_unique')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('teams',
    sa.Column('organization_name', sa.String(length=100), nullable=False),
    sa.Column('member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("position IN ('head', 'member')", name='teams_position_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('organization_name', 'member_id'),
    sa.UniqueConstraint('organization_name', 'email', name='teams_org_email_unique')
    )
    op.create_table('tasks',
    sa.Column('organization_name', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('task_deadline', sa.Date(), nullable=True),
    sa.Column('task_assigned_to', sa.Integer(), nullable=False),
    sa.Column('task_importance', sa.String(length=50), nullable=True),
    sa.Column('task_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("task_importance IN ('high', 'medium', 'low') OR task_importance IS NULL", name='tasks_importance_check'),
    sa.ForeignKeyConstraint(['organization_name', 'project_id'], ['projects.organization_name', 'projects.project_id'], name='tasks_project_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_name', 'task_assigned_to'], ['teams.organization_name', 'teams.member_id'], name='tasks_assignee_fk', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('organization_name', 'project_id', 'task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('teams')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
